# Generated by Django 3.2 on 2021-05-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0004_alter_event_event_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventGame',
            new_name='EventGamer',
        ),
        migrations.RenameField(
            model_name='gametype',
            old_name='name',
            new_name='label',
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='attending', through='levelupapi.EventGamer', to='levelupapi.Gamer'),
        ),
    ]
