# Generated by Django 3.2 on 2021-05-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0005_auto_20210504_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='title',
        ),
    ]
